export type PortfolioCategory = 'branding' | 'photoshoot' | 'packaging' | 'long' | 'short';

export interface PortfolioItem {
  id: string;
  category: PortfolioCategory;
  span2?: boolean;
  aspectRatio: string;
  fit?: 'cover' | 'contain';
  type: 'video' | 'image';
  src: string;
  duration?: string;
  title: string;
  label: string;
}

export const filters: { key: 'all' | PortfolioCategory; label: string; countLabel: string }[] = [
  { key: 'all', label: 'All work', countLabel: 'pieces' },
  { key: 'branding', label: 'Branding', countLabel: 'branding projects' },
  { key: 'photoshoot', label: 'Photoshoot', countLabel: 'shoots' },
  { key: 'packaging', label: 'Packaging', countLabel: 'packaging projects' },
  { key: 'long', label: 'Long video', countLabel: 'films' },
  { key: 'short', label: 'Short video', countLabel: 'reels' },
];

export const portfolioItems: PortfolioItem[] = [
  // Long form films
  {
    id: 'vedang-rathore',
    category: 'long',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786473746/vidssave.com_Major_Mohit_Sharma__The_Spy_Who_Infiltrated_Kashmir_s_Deadliest_Terror_Network___Dhurandhar_480P_onwwyo.mp4',
    title: 'Vedang Rathore — The Dhurandhar Story',
    label: 'Storytelling — Documentary',
  },
  {
    id: 'ms-design-studio',
    category: 'long',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786474057/vidssave.com_3_Acre_Sustainable_Farmhouse_in_Vadodara___Vernacular_Architecture_Eco-Friendly_Design_480P_n5hcko.mp4',
    title: 'MS Design Studio — The Vernacular Farmhouse',
    label: 'Architecture — Documentary',
  },
  {
    id: 'sumit-kapadia-arteries',
    category: 'long',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786473730/vidssave.com_I_ve_Operated_on_1000_Blocked_Arteries_This_Hidden_Ingredient_Was_in_EVERY_Patient_s_Diet_360P_dbguqj.mp4',
    title: 'Dr. Sumit Kapadia — 1,000 Blocked Arteries',
    label: 'Healthcare — Long Form',
  },
  {
    id: 'mithun-panchal',
    category: 'long',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786555893/vidssave.com_The_Real_Reason_Shah_Rukh_Khan_Still_Has_Thick_Hair_at_60_360P_ktnzlg.mp4',
    title: 'Dr Mithun Panchal — The Shah Rukh Khan Hair Secret',
    label: 'Healthcare — Long Form',
  },
  {
    id: 'surbhi-kapadia',
    category: 'long',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786473727/vidssave.com_Eyes_Par_Yellow_Patch__Yeh_High_Cholesterol_Ka_Warning_Sign_Hai_Xanthelasma_Truth_480P_zsxocz.mp4',
    title: 'Dr. Surbhi Kapadia — The Xanthelasma Truth',
    label: 'Healthcare — Long Form',
  },

  // Short form reels
  {
    id: 'ayushi-clairveda',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553225/Video-59256_f9vyja.mp4',
    title: "Ayushi | Founder Ayu's Clairveda",
    label: 'Cinematic Ad',
  },
  {
    id: 'sumit-kapadia-varicose',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553205/Varicose_Vein_EXPERT_Shares_Top_3_Exercises_for_Relief_ghxgtx.mp4',
    title: 'Dr Sumit Kapadia | Vascular Surgeon',
    label: '3.6M Views | 380K Subscribers',
  },
  {
    id: 'rajvi-cinematic-1',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553180/Video-38021_hhhbkc.mp4',
    title: 'Rajvi | Co-Founder Marca Creatives',
    label: 'Cinematic Ad',
  },
  {
    id: 'rajvi-cinematic-2',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553181/Video-81552_skecuv.mp4',
    title: 'Rajvi | Co-Founder Marca Creatives',
    label: 'Cinematic Ad',
  },
  {
    id: 'sandip-mavani-short',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553287/5.7M_1_r2lysy.mp4',
    title: 'Dr Sandip Mavani | Neurosurgeon',
    label: '5.7M Views | 49K Followers',
  },
  {
    id: 'eos-couture',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553217/Video-12950_kemi72.mp4',
    title: 'EOS Couture',
    label: 'Ad Campaign',
  },
  {
    id: 'frenzy-couture',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553000/Video-71601_agafjd.mp4',
    title: 'Frenzy Couture',
    label: 'Fashion Reels',
  },
  {
    id: 'nutty-affair-short',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553006/Video-95206_dmsnpi.mp4',
    title: 'Nutty Affair',
    label: 'Ad Campaign',
  },
  {
    id: 'aditya-shah-short',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553011/Video-54738_z4yoen.mp4',
    title: 'Dr. Aditya Shah | Dermatologist',
    label: '3M+ Views | 85K Followers',
  },
  {
    id: 'aadicura-short',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553046/Video-24171_zi192s.mp4',
    title: 'Aadicura Hospital',
    label: '43M+ Views | 1.2M+ Likes',
  },
  {
    id: 'preay-mehta',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786555487/Video-58265_imt14r.mp4',
    title: 'Dr Preay Mehta | Dentist',
    label: '2.9M Views | 23K Followers',
  },
  {
    id: 'nachiket-kaneria',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786555496/Video-18727_er0ho2.mp4',
    title: 'Dr. Nachiket Kaneria | Interventional Radiologist',
    label: '490K Views',
  },

  // Packaging
  {
    id: 'nutty-seeds-berries',
    category: 'packaging',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607756/1_2_yk2t4j.jpg',
    title: 'Nutty Affair — Seeds & Berries',
    label: 'Pouch Packaging',
  },
  {
    id: 'nutty-mukhwas',
    category: 'packaging',
    span2: true,
    aspectRatio: '4 / 3',
    fit: 'contain',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607755/BOOK_qmgybt.jpg',
    title: 'Nutty Affair — Mukhwas System',
    label: 'Tube Packaging',
  },
  {
    id: 'nutty-dehydrated-fruits',
    category: 'packaging',
    span2: true,
    aspectRatio: '4 / 3',
    fit: 'contain',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607741/FRUITS_MAGAZINE_tgo2hn.jpg',
    title: 'Nutty Affair — Dehydrated Fruits',
    label: 'Box Packaging',
  },
  {
    id: 'celebration-gift-box',
    category: 'packaging',
    aspectRatio: '4 / 3',
    fit: 'contain',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607738/WhatsApp_Image_2021-02-12_at_3.55.13_AM_20_f5w1vq.jpg',
    title: 'Celebration Gifting Box',
    label: 'Packaging',
  },
  {
    id: 'nutty-immunity-booster',
    category: 'packaging',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690577/1_3_uqbcwk.jpg',
    title: 'Nutty Affair — Immunity Booster',
    label: 'Pouch Packaging',
  },
  {
    id: 'nutty-berry-nuts',
    category: 'packaging',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690575/1_4_onx4hk.jpg',
    title: 'Nutty Affair — Berry Nuts',
    label: 'Pouch Packaging',
  },
  {
    id: 'nutty-foxnuts-chilli-cheese',
    category: 'packaging',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690564/WhatsApp_Image_2021-02-12_at_3.55.13_AM_21_xpfglv.jpg',
    title: 'Nutty Affair — Fox Nuts, Chilli & Cheese',
    label: 'Tin Packaging',
  },
  {
    id: 'nutty-foxnuts-peri-peri',
    category: 'packaging',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690563/WhatsApp_Image_2021-02-12_at_3.55.13_AM_22_nwaekj.jpg',
    title: 'Nutty Affair — Fox Nuts, Peri Peri',
    label: 'Tin Packaging',
  },
  {
    id: 'chini-kam-toucan-box',
    category: 'packaging',
    span2: true,
    aspectRatio: '3 / 2',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690587/3_aupud4.jpg',
    title: 'Chini Kam — Toucan Gift Box',
    label: 'Gift Box',
  },
  {
    id: 'chini-kam-botanical-box',
    category: 'packaging',
    aspectRatio: '3 / 2',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690576/1_pbzryg.jpg',
    title: 'Chini Kam — Botanical Gift Box',
    label: 'Gift Box',
  },
  {
    id: 'chini-kam-rajasthan-box',
    category: 'packaging',
    aspectRatio: '4 / 3',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690563/WhatsApp_Image_2021-02-12_at_3.55.13_AM_11_w0yq0w.jpg',
    title: 'Chini Kam — Rajasthan Edition Box',
    label: 'Gift Box',
  },
  {
    id: 'chini-kam-paris-box',
    category: 'packaging',
    aspectRatio: '4 / 3',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690563/WhatsApp_Image_2021-02-12_at_3.55.13_AM_13_solwfn.jpg',
    title: 'Chini Kam — Paris Edition Box',
    label: 'Gift Box',
  },
  {
    id: 'chini-kam-teal-box',
    category: 'packaging',
    aspectRatio: '4 / 3',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690573/2_1_hm1t7d.jpg',
    title: 'Chini Kam — Teal Leaf Gift Box',
    label: 'Gift Box',
  },
  {
    id: 'chini-kam-marble-box',
    category: 'packaging',
    aspectRatio: '4 / 3',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690570/3_2_djfibq.jpg',
    title: 'Chini Kam — Marble Gift Box',
    label: 'Gift Box',
  },
  {
    id: 'chini-kam-heritage-box',
    category: 'packaging',
    span2: true,
    aspectRatio: '3 / 2',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690563/WhatsApp_Image_2021-02-12_at_3.55.13_AM_16_nafp2t.jpg',
    title: 'Chini Kam — Heritage Skyline Box',
    label: 'Gift Box',
  },
  {
    id: 'chini-kam-floral-box',
    category: 'packaging',
    aspectRatio: '4 / 3',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690563/WhatsApp_Image_2021-02-12_at_3.55.13_AM_9_m7xkur.jpg',
    title: 'Chini Kam — Floral Motif Box',
    label: 'Gift Box',
  },
  {
    id: 'chini-kam-ivory-castle-box',
    category: 'packaging',
    aspectRatio: '4 / 3',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690563/WhatsApp_Image_2021-02-12_at_3.55.13_AM_14_evhxvw.jpg',
    title: 'Chini Kam — Ivory Castle Box',
    label: 'Gift Box',
  },
  {
    id: 'chini-kam-mumbai-box',
    category: 'packaging',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690562/WhatsApp_Image_2021-02-12_at_3.55.13_AM_4_ex5kgg.jpg',
    title: 'Chini Kam — Mumbai Skyline Box',
    label: 'Gift Box',
  },
  {
    id: 'chini-kam-noir-castle-box',
    category: 'packaging',
    aspectRatio: '4 / 3',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786690563/WhatsApp_Image_2021-02-12_at_3.55.13_AM_15_hxcgf3.jpg',
    title: 'Chini Kam — Noir Castle Box',
    label: 'Gift Box',
  },

  // Photoshoot
  {
    id: 'picnic-lifestyle',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786608765/ChatGPT_Image_Jul_16_2026_05_41_45_PM_hox3lo.png',
    title: 'Picnic Set Launch',
    label: 'Lifestyle',
  },
  {
    id: 'bridal-lehenga',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786608769/ChatGPT_Image_Jul_16_2026_06_10_05_PM_c7dwfy.png',
    title: 'Bridal Lehenga Editorial',
    label: 'Fashion',
  },
  {
    id: 'moody-cookies',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607738/ChatGPT_Image_Jul_16_2026_06_08_31_PM_ckdz6t.png',
    title: 'Moody Edits',
    label: 'Food',
  },
  {
    id: 'dessert-relaunch',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607737/ChatGPT_Image_Jul_16_2026_06_02_05_PM_zx5xye.png',
    title: 'Dessert Menu Relaunch',
    label: 'Food',
  },
  {
    id: 'menswear-campaign',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607737/ChatGPT_Image_Jul_16_2026_05_55_07_PM_nx1dgt.png',
    title: 'Festive Menswear Campaign',
    label: 'Fashion',
  },
  {
    id: 'menswear-duo',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607736/ChatGPT_Image_Jul_16_2026_05_53_26_PM_c90ttf.png',
    title: 'Menswear Portrait Duo',
    label: 'Fashion',
  },
  {
    id: 'menswear-everyday',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607732/ChatGPT_Image_Jul_16_2026_05_53_35_PM_oewfwt.png',
    title: 'Everyday Menswear Campaign',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-bridal-trio-field',
    category: 'photoshoot',
    span2: true,
    aspectRatio: '3 / 2',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691250/ChatGPT_Image_Aug_12_2026_02_26_19_PM_puys6a.png',
    title: 'Bridal Trio — Golden Field',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-picnic-tasting',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691249/ChatGPT_Image_Jul_16_2026_05_44_31_PM_vzikkk.png',
    title: 'Picnic Set — Tasting Notes',
    label: 'Lifestyle',
  },
  {
    id: 'photoshoot-picnic-garden-table',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691249/ChatGPT_Image_Jul_16_2026_05_49_43_PM_bcha6s.png',
    title: 'Picnic Set — Garden Table',
    label: 'Lifestyle',
  },
  {
    id: 'photoshoot-bridal-horse',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691250/ChatGPT_Image_Aug_12_2026_02_37_26_PM_kvolqv.png',
    title: 'Bridal Portrait — With Horse',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-field-silver-plum',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691249/ChatGPT_Image_Aug_12_2026_02_28_16_PM_zlxq2x.png',
    title: 'Field Portrait — Silver & Plum',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-harvest-standing',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691249/ChatGPT_Image_Aug_12_2026_02_31_27_PM_h7z2bq.png',
    title: 'Harvest Gown — Standing',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-harvest-seated',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691249/ChatGPT_Image_Aug_12_2026_02_36_09_PM_u1vznk.png',
    title: 'Harvest Gown — Seated',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-palace-sherwani',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691248/ChatGPT_Image_Jul_16_2026_05_56_38_PM_earsyc.png',
    title: 'Palace Sherwani Portrait',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-bridal-duo-mintred',
    category: 'photoshoot',
    span2: true,
    aspectRatio: '3 / 2',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691248/ChatGPT_Image_Jul_16_2026_06_12_10_PM_hakt6w.png',
    title: 'Bridal Duo — Mint & Red',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-menswear-asthetic',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691248/ChatGPT_Image_Jul_16_2026_06_00_57_PM_eneitn.png',
    title: 'Menswear Campaign — Asthetic',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-menswear-tecido',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691248/ChatGPT_Image_Jul_16_2026_06_00_50_PM_csa2tw.png',
    title: 'Menswear Campaign — Tecido',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-picnic-afternoon',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691248/ChatGPT_Image_Jul_16_2026_05_51_43_PM_yloraq.png',
    title: 'Picnic Set — Afternoon Rest',
    label: 'Lifestyle',
  },
  {
    id: 'photoshoot-bridal-duo-courtyard',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691166/ChatGPT_Image_Jul_16_2026_06_12_37_PM_qcutji.png',
    title: 'Bridal Duo — Courtyard',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-jewelry-concrete',
    category: 'photoshoot',
    aspectRatio: '4 / 3',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691128/ChatGPT_Image_Jul_16_2026_06_24_24_PM_werpqs.png',
    title: 'Concrete & Gold Jewelry',
    label: 'Product',
  },
  {
    id: 'photoshoot-field-duo-greenpink',
    category: 'photoshoot',
    span2: true,
    aspectRatio: '3 / 2',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691128/ChatGPT_Image_Jul_16_2026_06_26_24_PM_nsgb7m.png',
    title: 'Field Duo — Green & Pink',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-striped-midi-field',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691125/ChatGPT_Image_Jul_17_2026_01_54_17_PM_likiyr.png',
    title: 'Striped Midi — Open Field',
    label: 'Lifestyle',
  },
  {
    id: 'photoshoot-jewelry-campaign',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691124/ChatGPT_Image_Jul_16_2026_06_23_08_PM_agyuxc.png',
    title: 'Jewelry Campaign Card',
    label: 'Product',
  },
  {
    id: 'photoshoot-coffee-friends',
    category: 'photoshoot',
    aspectRatio: '4 / 3',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691121/ChatGPT_Image_Jul_17_2026_01_55_35_PM_btygsz.png',
    title: 'Coffee Table — Two Friends',
    label: 'Lifestyle',
  },
  {
    id: 'photoshoot-sequin-studio',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691120/ChatGPT_Image_Jul_17_2026_12_51_06_PM_rguzdl.png',
    title: 'Sequin Train — Studio',
    label: 'Fashion',
  },
  {
    id: 'photoshoot-striped-midi-golden',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691119/ChatGPT_Image_Jul_17_2026_01_57_00_PM_lzspne.png',
    title: 'Striped Midi — Golden Hour',
    label: 'Lifestyle',
  },
  {
    id: 'photoshoot-sequin-rooftop',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786691119/ChatGPT_Image_Jul_17_2026_12_46_26_PM_m2yck9.png',
    title: 'Sequin Train — Rooftop',
    label: 'Fashion',
  },

  // Branding
  {
    id: 'aadicura-label-system',
    category: 'branding',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1785487014/5_rnslzq.png',
    title: 'Aadicura Hospital — Label System',
    label: 'Identity',
  },
  {
    id: 'aadicura-identity-applied',
    category: 'branding',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1785487254/9_1_drw2xh.jpg',
    title: 'Aadicura Hospital — Identity Applied',
    label: 'Brand Identity',
  },
  {
    id: 'ledgerloop-social-system',
    category: 'branding',
    aspectRatio: '1 / 1',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1785486926/4_c5ql8a.png',
    title: 'Ledgerloop — Social Design System',
    label: 'Design System',
  },
];
