export type PortfolioCategory = 'branding' | 'photoshoot' | 'packaging' | 'long' | 'short';

export interface PortfolioItem {
  id: string;
  category: PortfolioCategory;
  span2?: boolean;
  aspectRatio: string;
  fit?: 'cover' | 'contain';
  type: 'video' | 'image';
  src: string;
  duration?: string;
  title: string;
  label: string;
}

export const filters: { key: 'all' | PortfolioCategory; label: string; countLabel: string }[] = [
  { key: 'all', label: 'All work', countLabel: 'pieces' },
  { key: 'branding', label: 'Branding', countLabel: 'branding projects' },
  { key: 'photoshoot', label: 'Photoshoot', countLabel: 'shoots' },
  { key: 'packaging', label: 'Packaging', countLabel: 'packaging projects' },
  { key: 'long', label: 'Long video', countLabel: 'films' },
  { key: 'short', label: 'Short video', countLabel: 'reels' },
];

export const portfolioItems: PortfolioItem[] = [
  // Long form films
  {
    id: 'vedang-rathore',
    category: 'long',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786473746/vidssave.com_Major_Mohit_Sharma__The_Spy_Who_Infiltrated_Kashmir_s_Deadliest_Terror_Network___Dhurandhar_480P_onwwyo.mp4',
    title: 'Vedang Rathore — The Dhurandhar Story',
    label: 'Storytelling — Documentary',
  },
  {
    id: 'ms-design-studio',
    category: 'long',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786474057/vidssave.com_3_Acre_Sustainable_Farmhouse_in_Vadodara___Vernacular_Architecture_Eco-Friendly_Design_480P_n5hcko.mp4',
    title: 'MS Design Studio — The Vernacular Farmhouse',
    label: 'Architecture — Documentary',
  },
  {
    id: 'sumit-kapadia-arteries',
    category: 'long',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786473730/vidssave.com_I_ve_Operated_on_1000_Blocked_Arteries_This_Hidden_Ingredient_Was_in_EVERY_Patient_s_Diet_360P_dbguqj.mp4',
    title: 'Dr. Sumit Kapadia — 1,000 Blocked Arteries',
    label: 'Healthcare — Long Form',
  },
  {
    id: 'mithun-panchal',
    category: 'long',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786555893/vidssave.com_The_Real_Reason_Shah_Rukh_Khan_Still_Has_Thick_Hair_at_60_360P_ktnzlg.mp4',
    title: 'Dr Mithun Panchal — The Shah Rukh Khan Hair Secret',
    label: 'Healthcare — Long Form',
  },
  {
    id: 'surbhi-kapadia',
    category: 'long',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786473727/vidssave.com_Eyes_Par_Yellow_Patch__Yeh_High_Cholesterol_Ka_Warning_Sign_Hai_Xanthelasma_Truth_480P_zsxocz.mp4',
    title: 'Dr. Surbhi Kapadia — The Xanthelasma Truth',
    label: 'Healthcare — Long Form',
  },

  // Short form reels
  {
    id: 'ayushi-clairveda',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553225/Video-59256_f9vyja.mp4',
    title: "Ayushi | Founder Ayu's Clairveda",
    label: 'Cinematic Ad',
  },
  {
    id: 'sumit-kapadia-varicose',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553205/Varicose_Vein_EXPERT_Shares_Top_3_Exercises_for_Relief_ghxgtx.mp4',
    title: 'Dr Sumit Kapadia | Vascular Surgeon',
    label: '3.6M Views | 380K Subscribers',
  },
  {
    id: 'rajvi-cinematic-1',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553180/Video-38021_hhhbkc.mp4',
    title: 'Rajvi | Co-Founder Marca Creatives',
    label: 'Cinematic Ad',
  },
  {
    id: 'rajvi-cinematic-2',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553181/Video-81552_skecuv.mp4',
    title: 'Rajvi | Co-Founder Marca Creatives',
    label: 'Cinematic Ad',
  },
  {
    id: 'sandip-mavani-short',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553287/5.7M_1_r2lysy.mp4',
    title: 'Dr Sandip Mavani | Neurosurgeon',
    label: '5.7M Views | 49K Followers',
  },
  {
    id: 'eos-couture',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553217/Video-12950_kemi72.mp4',
    title: 'EOS Couture',
    label: 'Ad Campaign',
  },
  {
    id: 'frenzy-couture',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553000/Video-71601_agafjd.mp4',
    title: 'Frenzy Couture',
    label: 'Fashion Reels',
  },
  {
    id: 'nutty-affair-short',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553006/Video-95206_dmsnpi.mp4',
    title: 'Nutty Affair',
    label: 'Ad Campaign',
  },
  {
    id: 'aditya-shah-short',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553011/Video-54738_z4yoen.mp4',
    title: 'Dr. Aditya Shah | Dermatologist',
    label: '3M+ Views | 85K Followers',
  },
  {
    id: 'aadicura-short',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786553046/Video-24171_zi192s.mp4',
    title: 'Aadicura Hospital',
    label: '43M+ Views | 1.2M+ Likes',
  },
  {
    id: 'preay-mehta',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786555487/Video-58265_imt14r.mp4',
    title: 'Dr Preay Mehta | Dentist',
    label: '2.9M Views | 23K Followers',
  },
  {
    id: 'nachiket-kaneria',
    category: 'short',
    aspectRatio: '9 / 16',
    type: 'video',
    src: 'https://res.cloudinary.com/ts350ak2/video/upload/v1786555496/Video-18727_er0ho2.mp4',
    title: 'Dr. Nachiket Kaneria | Interventional Radiologist',
    label: '490K Views',
  },

  // Packaging
  {
    id: 'nutty-seeds-berries',
    category: 'packaging',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607756/1_2_yk2t4j.jpg',
    title: 'Nutty Affair — Seeds & Berries',
    label: 'Pouch Packaging',
  },
  {
    id: 'nutty-mukhwas',
    category: 'packaging',
    span2: true,
    aspectRatio: '4 / 3',
    fit: 'contain',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607755/BOOK_qmgybt.jpg',
    title: 'Nutty Affair — Mukhwas System',
    label: 'Tube Packaging',
  },
  {
    id: 'nutty-dehydrated-fruits',
    category: 'packaging',
    span2: true,
    aspectRatio: '4 / 3',
    fit: 'contain',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607741/FRUITS_MAGAZINE_tgo2hn.jpg',
    title: 'Nutty Affair — Dehydrated Fruits',
    label: 'Box Packaging',
  },
  {
    id: 'celebration-gift-box',
    category: 'packaging',
    aspectRatio: '4 / 3',
    fit: 'contain',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607738/WhatsApp_Image_2021-02-12_at_3.55.13_AM_20_f5w1vq.jpg',
    title: 'Celebration Gifting Box',
    label: 'Packaging',
  },

  // Photoshoot
  {
    id: 'picnic-lifestyle',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786608765/ChatGPT_Image_Jul_16_2026_05_41_45_PM_hox3lo.png',
    title: 'Picnic Set Launch',
    label: 'Lifestyle',
  },
  {
    id: 'bridal-lehenga',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786608769/ChatGPT_Image_Jul_16_2026_06_10_05_PM_c7dwfy.png',
    title: 'Bridal Lehenga Editorial',
    label: 'Fashion',
  },
  {
    id: 'moody-cookies',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607738/ChatGPT_Image_Jul_16_2026_06_08_31_PM_ckdz6t.png',
    title: 'Moody Edits',
    label: 'Food',
  },
  {
    id: 'dessert-relaunch',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607737/ChatGPT_Image_Jul_16_2026_06_02_05_PM_zx5xye.png',
    title: 'Dessert Menu Relaunch',
    label: 'Food',
  },
  {
    id: 'menswear-campaign',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607737/ChatGPT_Image_Jul_16_2026_05_55_07_PM_nx1dgt.png',
    title: 'Festive Menswear Campaign',
    label: 'Fashion',
  },
  {
    id: 'menswear-duo',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607736/ChatGPT_Image_Jul_16_2026_05_53_26_PM_c90ttf.png',
    title: 'Menswear Portrait Duo',
    label: 'Fashion',
  },
  {
    id: 'menswear-everyday',
    category: 'photoshoot',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1786607732/ChatGPT_Image_Jul_16_2026_05_53_35_PM_oewfwt.png',
    title: 'Everyday Menswear Campaign',
    label: 'Fashion',
  },

  // Branding
  {
    id: 'aadicura-label-system',
    category: 'branding',
    aspectRatio: '4 / 5',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1785487014/5_rnslzq.png',
    title: 'Aadicura Hospital — Label System',
    label: 'Identity',
  },
  {
    id: 'aadicura-identity-applied',
    category: 'branding',
    span2: true,
    aspectRatio: '16 / 9',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1785487254/9_1_drw2xh.jpg',
    title: 'Aadicura Hospital — Identity Applied',
    label: 'Brand Identity',
  },
  {
    id: 'ledgerloop-social-system',
    category: 'branding',
    aspectRatio: '1 / 1',
    type: 'image',
    src: 'https://res.cloudinary.com/ts350ak2/image/upload/f_auto,q_auto,w_1100/v1785486926/4_c5ql8a.png',
    title: 'Ledgerloop — Social Design System',
    label: 'Design System',
  },
];
